<script lang="ts">

    // --- Components ---
	import { Flex } from '@root/lib/ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';
	import { onMount } from 'svelte';
	import type { Program } from '@root/lib/internal/types';
	import { getIdentityCtx } from '@root/lib/ctx';
	import { State } from '@root/lib/internal';
	import { goto } from '$app/navigation';

	let {
		children,
		class: className,
		programLinkClass = $bindable('items-center bg-app justify-center text-white py-5 rounded-[1rem] w-full'),
		slug = $bindable(undefined)
	}: Props = $props();

	// Setup ProgramLink's class
	let programLinkCls = $state(cn(programLinkClass, className));
	$effect(() => {
		programLinkCls = cn(programLinkClass, className);
	});

	let program: Program | undefined = $state(undefined);
	let load_state: State = $state(new State());

	const { user } = getIdentityCtx();

	onMount(async () => {
		if (!slug) return;
		const _program = await user.get_program(slug);
		program = _program;
		load_state.flagLoaded();
	});

	async function handleClick() {
		if (!slug) return;
		if (!program?.slug) return;
		goto(`/programs/${program.slug}`);
	}
</script>

<Flex.Col class={programLinkCls} onclick={handleClick}>
	{#if load_state.value == 'loading'}
		<h4>Loading</h4>
	{/if}

	{#if load_state.value == 'loaded'}
		<h3 class="text-white text-[1.75rem] opacity-100">Visit Program</h3>
	{/if}
</Flex.Col>

<!--@component
    Generated by SvelteForge🔥
-->
