<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        flexClass = $bindable('flex'),
        ...rest
    }: Props = $props();


    // Setup Flex's class
    let flexCls = $state(cn(flexClass, className));
    $effect(() => {
        flexCls = cn(flexClass, className)
    })

</script>

<div class={ flexCls } {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

