<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ColProps } from ".."
    
    let {
        children,
        class: className,
        colClass = $bindable('flex flex-col'),
        ...rest
    }: ColProps = $props();


    // Setup Col's class
    let colCls = $state(cn(colClass, className));
    $effect(() => {
        colCls = cn(colClass, className)
    })

</script>

<div class={ colCls } {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

