<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import { type Props, Colors, Sizes } from '..';

	let {
		children,
		class: className,
		color = $bindable('black'),
		size = $bindable('base'),
		...rest
	}: Props = $props();

	let colorCls = Colors[color];
	let sizeCls = Sizes[size];
	let buttonCls = cn(`rounded-md cursor-pointer w-fit items-center justify-center`, colorCls, sizeCls)
</script>

<button class={cn(buttonCls, className)} {...rest}>
	{@render children?.()}
</button>

<!--@component
    Generated by SvelteForge🔥
-->
