<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import { type Props, Colors, Shapes, Sizes } from '..';
	import { Container } from '@root/lib/ui';

	let {
		children,
		class: className,
		color = $bindable('black'),
		size = $bindable('base'),
		mode = $bindable('fill'),
		shape = $bindable('rounded'),
		text = $bindable(undefined),
		href = $bindable(undefined),
		onclick = $bindable(() => {}),
		...rest
	}: Props = $props();

	let colorCls = cn(mode == 'fill' && 'bg-current', mode == 'outline' && 'border border-2');

	let sizeCls = Sizes[size];
	let shapeCls = Shapes[shape];

	let buttonCls = cn(
		`cursor-pointer w-fit`,
		colorCls,
		sizeCls,
		shapeCls
	);

	let anchor_ref: HTMLAnchorElement | undefined = $state(undefined)

	function handleClick(event: MouseEvent) {
		// Run onclick specified if exists
		if (onclick) {onclick(event as any)};
		
		if (!anchor_ref) return;

		// Simulate Click
		anchor_ref.click();

	}
</script>

<!-- svelte-ignore element_invalid_self_closing_tag -->
<!-- svelte-ignore a11y_consider_explicit_label -->
<a {href} class="hidden" bind:this={anchor_ref}/>

<button class={cn(buttonCls, className)} {...rest} onclick={handleClick}>
	<Container class={cn("items-center justify-center flex flex-row gap-4 [&_>_svg]:size-7", mode== 'fill' && 'text-white')}>
		{@render children?.()}

		{#if text}
			<h3 class="leading-none text-current text-[1.5rem]">{text}</h3>
		{/if}
	</Container>
</button>

<!--@component
    Generated by SvelteForge🔥
-->
