<script lang="ts">

    // --- Logic ---
    import { cn, cn_a } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        eventCardClass = $bindable(''),
        data = $bindable(undefined)
    }: Props = $props();


    // Setup EventCard's class
    let eventCardCls = $state(cn(eventCardClass, className));
    $effect(() => {
        eventCardCls = cn(eventCardClass, className)
    })


    data?.card.color // This arg here

</script>

<div class={ cn(eventCardCls, cn_a.buildx("highlighted", "bg-red-400")) } data-highlighted>
    <img src={data?.card.image.url || null} alt={`${data?.name} Card Image`}/>
    <h2>{data?.name}</h2>
    <h3>{data?.description}</h3>
    <button>Learn More</button>
</div>

<style scoped>



</style>

<!--@component
    Generated by SvelteForge🔥
-->

