<script lang="ts">
	// --- Logic ---
	import { cn, cn_a } from '@lib/utils';
	import type { Props } from '..';

	// Destructure component props with default bindings
	let {
		children,
		class: className,
		eventCardClass = $bindable(''),
		data = $bindable(undefined)
	}: Props = $props();

	// Compute merged className for the event card
	let eventCardCls = $state(cn(eventCardClass, className));
	$effect(() => {
		eventCardCls = cn(eventCardClass, className);
	});
</script>

<!-- Root container with optional highlight styling -->
<div class={cn(eventCardCls, cn_a.buildx('highlighted', 'bg-red-400'))} data-highlighted>
	<!-- Card Image -->
	<img
		src={data?.card.image.url || null}
		alt={`${data?.name} Card Image`}
		style={data?.card.image.style}
	/>

	<div class="card-information">
		<!-- Card Title & Description -->
		<h3>{data?.name}</h3>
		<h4>{data?.description}</h4>

		<!-- Link to event detail page -->
		<a href={`/events/${data?.slug}`} class="flex w-full">
			<!-- Button styled with dynamic event color -->
			<button class="text-white py-5 rounded-[1rem] w-full" style={`background: ${data?.card.color};`}>
				<h4>Learn More</h4>
			</button>
		</a>
	</div>
</div>

<style scoped>
	/* Root Event Card Container */
	div {
		@apply w-full overflow-hidden;
		border-radius: calc(var(--spacing) * 8);
		box-shadow: 0px 1px 1px 0px rgba(0, 0, 0, 0.25);

		/* Card Image */
		& img {
			@apply w-full object-cover;
			aspect-ratio: 2/1;
			border-radius: calc(var(--spacing) * 8);
		}

		/* Card Content Block */
		& .card-information {
			@apply flex flex-col box-border;
			gap: calc(var(--spacing) * 6);
			padding: calc(var(--spacing) * 10);

			/* Multi-line text clamp on description */
			& h4 {
				display: -webkit-box;
				-webkit-line-clamp: 3;
				line-clamp: 2;
				-webkit-box-orient: vertical;
				overflow: hidden;
			}
		}
	}
</style>

<!--@component
	Represents a clickable card showing event info and linking to event details.
	Generated by SvelteForge🔥
-->
