<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';
	import { getColorCtx } from '@root/lib/ctx';
	import { onMount } from 'svelte';

	let {
		children,
		class: className,
		programCardClass = $bindable(''),
		data = $bindable(undefined)
	}: Props = $props();

	// Get Color Context
	const { color$ } = getColorCtx();

	// Setup ProgramCard's class
	let programCardCls = $state(cn(programCardClass, className));
	$effect(() => {
		programCardCls = cn(programCardClass, className);
	});

	let ref_card: HTMLDivElement | undefined = $state(undefined);

	// Intersection Checking
	onMount(() => {
		if (!ref_card) return;

		/**
		 * Set up the callback responsible for listening for "intersections"
		 * @param entries
		 * @param observer
		 */
		function callback(entries: IntersectionObserverEntry[], observer: IntersectionObserver) {
			// Gather Component Information
			const entry: IntersectionObserverEntry = entries[0];
			const rect = entry.boundingClientRect;
			const windowHeight = window.innerHeight || document.documentElement.clientHeight;

			// Check if bottom visible
			if (Math.round(rect.bottom - 50) <= windowHeight) {
				console.warn(`Bottom visible of ${data?.slug}`);
				color$.set(data?.card.color || null);
			}
		}

		/**
		 * Setup the options for the observer.
		 */
		const options: IntersectionObserverInit = {
			root: null,
			threshold: 1
		};

		const observer = new IntersectionObserver(callback, options);

		observer.observe(ref_card);

		// Cleanup
		return () => {
			observer.disconnect();
		};
	});
</script>

<!-- Root container with optional highlight styling -->
<div
	bind:this={ref_card}
	class={cn(programCardCls, cn('highlighted', 'bg-red-400'))}
	data-highlighted
>
	<!-- Card Image -->
	<img
		src={data?.card.image.url || null}
		alt={`${data?.name} Card Image`}
		style={data?.card.image.style}
	/>

	<div class="card-information">
		<!-- Card Title & Description -->
		<h3>{data?.name}</h3>
		<h4>{data?.description}</h4>

		<!-- Link to program detail page -->
		<a href={`/programs/${data?.slug}`} class="flex w-full">
			<!-- Button styled with dynamic program color -->
			<button
				class="text-white py-5 rounded-[1rem] w-full"
				style={`background: ${data?.card.color};`}
			>
				<h4>Learn More</h4>
			</button>
		</a>
	</div>
</div>

<!--@component
    Represents a clickable card showing program info and linking to program details.
    Generated by SvelteForge🔥
-->

<style scoped>
	/* Root Event Card Container */
	div {
		@apply w-full overflow-hidden;
		border-radius: calc(var(--spacing) * 8);
		box-shadow: 0px 1px 1px 0px rgba(0, 0, 0, 0.25);

		/* Card Image */
		& img {
			@apply w-full object-cover;
			aspect-ratio: 2/1;
			border-radius: calc(var(--spacing) * 8);
		}

		/* Card Content Block */
		& .card-information {
			@apply flex flex-col box-border;
			gap: calc(var(--spacing) * 6);
			padding: calc(var(--spacing) * 10);

			/* Multi-line text clamp on description */
			& h4 {
				display: -webkit-box;
				-webkit-line-clamp: 3;
				line-clamp: 2;
				-webkit-box-orient: vertical;
				overflow: hidden;
			}
		}
	}
</style>
