<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';
	import { getIdentityCtx } from '@root/lib/ctx';

	// Get dev_admin$ context
	const { dev_admin$ } = getIdentityCtx();

	// Reactive state for admin access
	let active_admin: boolean | null = $state(null);
	dev_admin$.subscribe((c) => (active_admin = c));

	let { children, class: className, adminOnlyClass = $bindable('') }: Props = $props();

	// Setup AdminOnly's class
	let adminOnlyCls = $state(cn(adminOnlyClass, className));
	$effect(() => {
		adminOnlyCls = cn(adminOnlyClass, className);
	});
</script>

{#if active_admin}
	<div class={adminOnlyCls}>
		{@render children?.()}
	</div>
{/if}

<!--@component
    Generated by SvelteForge🔥
-->
