<script lang="ts">

    // --- Components ---
    import IconEdit from '~icons/material-symbols/edit';

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
	import { Flex } from '@root/lib/ui';
	import { goto } from '$app/navigation';
    
    
    let {
        children,
        class: className,
        editClass = $bindable('')
    }: Props = $props();

    // Slug data object
	import { page } from '$app/state';
	const slug = page.params.slug;

    // Setup Edit's class
    let editCls = $state(cn(editClass, className));
    $effect(() => {
        editCls = cn(editClass, className)
    })

    

    async function edit() {
        goto(`/events/${slug}/edit`)
    }

</script>

<Flex.Col class={cn(`border-5 border-app bg-white size-30 rounded-full fixed bottom-60 right-10 z-100000 items-center justify-center`)} onclick={edit}>
    <IconEdit class="size-[60%] text-app"/>
</Flex.Col>

<!--@component
    Generated by SvelteForge🔥
-->

