<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        containerClass = $bindable(''),
        ...rest
    }: Props = $props();


    // Setup Container's class
    let containerCls = $state(cn(containerClass, className));
    $effect(() => {
        containerCls = cn(containerClass, className)
    })

</script>

<div class={ containerCls } {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->