<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils'; // Utility function for handling class names
	import type { Props } from '..'; // Importing the Props type for type safety

	// Define props with default values, using $bindable for reactivity
	let {
		children, // Slot content (if any)
		class: className, // Custom class passed to the component
		toggleClass = $bindable(
			'flex flex-col w-20 h-10 rounded-full bg-gray-500 box-border cursor-pointer justify-center animate animate-all px-2'
		), // Default styling for the toggle switch
		value = $bindable(false), // Reactive boolean state for toggle
		onupdate: onchange = $bindable(() => {}), // Callback triggered on toggle change
		ontrue = $bindable(() => {}), // Callback triggered when value becomes true
		onfalse = $bindable(() => {}), // Callback triggered when value becomes false
		...rest // Any additional props passed to the component
	}: Props = $props();

	// Compute the class name for the toggle
	let toggleCls = $state(cn(toggleClass, className));

	// Ensure class updates reactively when toggleClass or className changes
	$effect(() => {
		toggleCls = cn(toggleClass, className);
	});

	// Handle toggle state change and invoke callbacks
	function internal_onclick() {
		value = !value;
		onchange(value); // Notify parent of value change

		if (value) {
			ontrue(); // Call ontrue callback if value is now true
		} else {
			onfalse(); // Call onfalse callback if value is now false
		}
	}
</script>

<!-- Toggle Container -->
<div class={cn(toggleCls, value && 'bg-primary')} {...rest} onclick={internal_onclick}>
	<!-- Swatch (the actual moving circle inside the toggle) -->
	<div
		class={cn(
			'bg-white size-6 rounded-full translate-x-0', // Default position
			value && 'ml-[calc(100%-8px)] -translate-x-[67%]' // Shift right when toggled
		)}
	></div>
</div>

<!-- @component
    Generated by SvelteForge🔥
-->
