<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';
	import IconCalendar from '~icons/solar/calendar-date-outline';
	import IconMap from '~icons/solar/map-outline';
	import IconGraduation from '~icons/fluent/hat-graduation-32-regular';
	import IconSettings from '~icons/solar/settings-outline';
	import IconMoney from '~icons/solar/money-bag-linear';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import { Item, type Props } from '..';

	// Capacitor Plugins
	import { CapacitorBarcodeScanner } from '@capacitor/barcode-scanner';
	import qrCodeResponseHandler from '@root/lib/internal/qr/qr';

	let {
		children,
		class: className,
		navigationClass = $bindable(
			`s_2xl:hidden s_xl:hidden s_lg:hidden 
			min-h-[13%] h-[10%] 
			box-border pt-0 
			justify-between items-end 
			px-[5%] w-full 
			box-border 
			text-black/60 z-999 border-t border-black/50 bg-white  pb-[var(--safe-area-inset-bottom)] p_ios:pb-10 `
		)
	}: Props = $props();

	// Setup Navigation's class
	let navigationCls = $state(cn(navigationClass, className));
	$effect(() => {
		navigationCls = cn(navigationClass, className);
	});

	async function qr_button_onclick() {
		const qr_res = await CapacitorBarcodeScanner.scanBarcode({
			hint: 0,
			cameraDirection: 1,
			scanOrientation: 1
		});

		qrCodeResponseHandler.run(qr_res.ScanResult);
	}
</script>

<Flex.Row class={navigationCls}>
	{@render children?.()}

	<Item href="/events">
		{#snippet icon()}
			<IconCalendar class="size-full" />
		{/snippet}
	</Item>

	<Item href="/pricemap">
		{#snippet icon()}
			<IconMoney class="size-full" />
		{/snippet}
	</Item>

	<Item href="/programs">
		{#snippet icon()}
			<IconGraduation class="size-full" />
		{/snippet}
	</Item>

	<Item href="/settings" class="text-inherit">
		{#snippet icon()}
			<IconSettings class="size-full" />
		{/snippet}
	</Item>
</Flex.Row>

<!--@component
    Generated by SvelteForge🔥
-->
