<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';
	import IconCalendar from '~icons/solar/calendar-date-outline';
	import IconMap from '~icons/solar/map-outline';
	import IconQRCode from '~icons/solar/qr-code-bold';
	import IconFolder from '~icons/solar/folder-outline';
	import IconSettings from '~icons/solar/settings-outline';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import { Item, type Props } from '..';

	// Capacitor Plugins
	import { CapacitorBarcodeScanner } from '@capacitor/barcode-scanner';

	let {
		children,
		class: className,
		navigationClass = $bindable(
			`s_2xl:hidden s_xl:hidden s_lg:hidden h-[15%] box-border pt-2 justify-between items-end px-[5%] self-center w-full box-border fixed bottom-0 text-black/60 z-999 border-t border-black/50 bg-white  pb-[var(--safe-area-inset-bottom)]`
		)
	}: Props = $props();

	// Setup Navigation's class
	let navigationCls = $state(cn(navigationClass, className));
	$effect(() => {
		navigationCls = cn(navigationClass, className);
	});

	async function qr_button_onclick() {
		const qr_res = await CapacitorBarcodeScanner.scanBarcode({
			hint: 0,
			cameraDirection: 1,
			scanOrientation: 1
		});
		console.log(qr_res.ScanResult);
	}
</script>

<Flex.Row class={navigationCls}>
	{@render children?.()}

	<Item href="/events">
		{#snippet icon()}
			<IconCalendar class="size-full" />
		{/snippet}
	</Item>

	<Item href="/map">
		{#snippet icon()}
			<IconMap class="size-full" />
		{/snippet}
	</Item>

	<Flex.Col
		class="bg-primary text-white aspect-square h-[70%] mb-[4%] rounded-full shrink-0 items-center justify-center"
		onclick={qr_button_onclick}
	>
		<IconQRCode class="size-[50%] shrink-0" />
	</Flex.Col>

	<Item href="/programs">
		{#snippet icon()}
			<IconFolder class="size-full" />
		{/snippet}
	</Item>

	<Item href="/settings" class="text-inherit">
		{#snippet icon()}
			<IconSettings class="size-full" />
		{/snippet}
	</Item>
</Flex.Row>

<!--@component
    Generated by SvelteForge🔥
-->
