<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { ItemProps } from '..';
	import { onMount } from 'svelte';
	import { afterNavigate, beforeNavigate, onNavigate } from '$app/navigation';

	let {
		children,
		class: className,

		// --- Default Classes
		itemClass = $bindable('items-center justify-center w-[7vw] aspect-square text-inherit'),
		iconClass = $bindable(`size-full mb-3 text-inherit shrink-0 animate`),

		// --- User Defined Classes
		classIcon = $bindable(``),

		// Extra Props Here:
		onclick = $bindable(undefined),
		href = $bindable(undefined),

		// Snippets Here:
		icon,
		...rest
	}: ItemProps = $props();

	// Setup Item's class
	let itemCls = $state(cn(itemClass, className));
	let iconCls = $state(cn(iconClass, classIcon));

	let active = $state(false)
	
	$effect(() => {
		itemCls = cn(itemClass, className);
		iconCls = cn(iconClass, classIcon);
	});

	// If this item should act as a link, replace the onclick method
	if (href) {
		onclick = () => {
			if (href == window.location.pathname) return;
			window.location.href = href;
		};
	}

	function check_active() {
		console.log("Firing", href == window.location.pathname, href, window.location.pathname)
		active = href == window.location.pathname
	}

	onMount(() => {
		// Check if state should be active
		check_active();
		console.log("on-mount")

		onNavigate(() => {
			console.log("on-navigate")
			check_active();
		})

	})
</script>

<a class={cn(itemCls, !icon && iconCls, active && 'text-primary')} {href} {...rest}>
	<!-- Icon Renderer -->
	{#if icon}
		<Flex.Col class={iconCls}>
			{@render icon?.()}
		</Flex.Col>
	{/if}

	{@render children?.()}
	</a>

<!--@component
    Generated by SvelteForge🔥
-->
