<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { ItemProps } from '..';

	let {
		children,
		class: className,

		// --- Default Classes
		itemClass = $bindable('items-center justify-center w-[7vw] aspect-square text-inherit'),
		iconClass = $bindable(`size-full mb-3 text-inherit shrink-0`),

		// --- User Defined Classes
		classIcon = $bindable(``),

		// Extra Props Here:
		onclick = $bindable(undefined),
		href = $bindable(undefined),

		// Snippets Here:
		icon
	}: ItemProps = $props();

	// Setup Item's class
	let itemCls = $state(cn(itemClass, className));
	let iconCls = $state(cn(iconClass, classIcon));

	$effect(() => {
		itemCls = cn(itemClass, className);
		iconCls = cn(iconClass, classIcon);
	});

	// If this item should act as a link, replace the onclick method
	if (href) {
		onclick = () => {
			window.location.href = href;
		};
	}
</script>

<Flex.Col class={cn(itemCls, !icon && iconCls)} {onclick}>
	<!-- Icon Renderer -->
	{#if icon}
		<Flex.Col class={iconCls}>
			{@render icon?.()}
		</Flex.Col>
	{/if}

	{@render children?.()}
</Flex.Col>

<!--@component
    Generated by SvelteForge🔥
-->
