<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';
	import IconCalendar from '~icons/solar/calendar-date-outline';
	import IconMap from '~icons/solar/map-outline';
	import IconQRCode from '~icons/solar/qr-code-bold';
	import IconFolder from '~icons/solar/folder-outline';
	import IconSettings from '~icons/solar/settings-outline';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import { Item, type Props } from '..';

	let {
		children,
		class: className,
		navigationClass = $bindable(
			`h-20 justify-between items-end self-center w-full h-fit box-border fixed bottom-[5%] px-[5%] text-black/60`
		)
	}: Props = $props();

	// Setup Navigation's class
	let navigationCls = $state(cn(navigationClass, className));
	$effect(() => {
		navigationCls = cn(navigationClass, className);
	});
</script>

<Flex.Row class={navigationCls}>
	{@render children?.()}

	<Item href="">
		{#snippet icon()}
			<IconCalendar class="size-full" />
		{/snippet}
	</Item>

	<Item href="">
		{#snippet icon()}
			<IconMap class="size-full" />
		{/snippet}
	</Item>

	<Flex.Col
		href=""
		class="bg-primary text-white aspect-square min-w-20 w-[20vw] rounded-full shrink-0 items-center justify-center"
	>
		<IconQRCode class="size-[50%] shrink-0" />
	</Flex.Col>

	<Item href="">
		{#snippet icon()}
			<IconFolder class="size-full" />
		{/snippet}
	</Item>

	<Item href="" class="text-inherit">
		{#snippet icon()}
			<IconSettings class="size-full" />
		{/snippet}
	</Item>
</Flex.Row>

<!--@component
    Generated by SvelteForge🔥
-->
