<script lang="ts">
	// --- Logic ---
	import { cn, cn_a } from '@lib/utils';
	import type { Props } from '..';
	import { onMount } from 'svelte';
	import { getColorCtx } from '@root/lib/ctx';
	import { goto } from '$app/navigation';

	// Destructure component props with default bindings
	let {
		children,
		class: className,
		eventCardClass = $bindable(''),
		data = $bindable(undefined)
	}: Props = $props();

	// Get Color Context
	const { color$ } = getColorCtx();

	// Compute merged className for the event card
	let eventCardCls = $state(cn(eventCardClass, className));
	$effect(() => {
		eventCardCls = cn(eventCardClass, className);
	});

	let ref_card: HTMLDivElement | undefined = $state(undefined);

	// Intersection Checking
	onMount(() => {
		if (!ref_card) return;

		/**
		 * Set up the callback responsible for listening for "intersections"
		 * @param entries
		 * @param observer
		 */
		function callback(entries: IntersectionObserverEntry[], observer: IntersectionObserver) {
			// Gather Component Information
			const entry: IntersectionObserverEntry = entries[0];
			const rect = entry.boundingClientRect;
			const windowHeight = window.innerHeight || document.documentElement.clientHeight;

			// Check if bottom visible
			if (Math.round(rect.bottom - 50) <= windowHeight) {
				console.warn(`Bottom visible of ${data?.slug}`);
				color$.set(data?.card.color || null)
			}
		}

		/**
		 * Setup the options for the observer.
		 */
		const options: IntersectionObserverInit = {
			root: null,
			threshold: 1
		};

		const observer = new IntersectionObserver(callback, options);

		observer.observe(ref_card);

		// Cleanup
		return () => {
			observer.disconnect();
		};
	});

	async function route_to() {
		goto(`/events/${data?.slug}`)
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- Root container with optional highlight styling -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div
	bind:this={ref_card}
	class={cn(eventCardCls)}
	onclick={route_to}
>
	<!-- Card Image -->
	<img
		src={data?.card.image.url || null}
		alt={`${data?.name} Card Image`}
		style={data?.card.image.style}
	/>

	<!-- svelte-ignore a11y_missing_attribute -->
	<div class="card-information">
		<!-- Card Title & Description -->
		<h3 class="text-center font-bold self-center">{data?.name}</h3>
		<h4>{data?.description}</h4>

		<!-- Link to event detail page -->
		<a class="flex w-full">
			<!-- Button styled with dynamic event color -->
			<button
				class="text-white py-5 rounded-[1rem] w-full"
				style={`background: ${data?.card.color};`}
			>
				<h4>Learn More</h4>
			</button>
		</a>
	</div>
</div>

<!--@component
	Represents a clickable card showing event info and linking to event details.
	Generated by SvelteForge🔥
-->

<style scoped>
	/* Root Event Card Container */
	div {
		@apply w-full overflow-hidden;
		border-radius: calc(var(--spacing) * 8);
		box-shadow: 0px 1px 1px 0px rgba(0, 0, 0, 0.25);

		/* Card Image */
		& img {
			@apply w-full object-cover;
			aspect-ratio: 2/1;
			border-radius: calc(var(--spacing) * 8);
		}

		/* Card Content Block */
		& .card-information {
			@apply flex flex-col box-border;
			gap: calc(var(--spacing) * 6);
			padding: calc(var(--spacing) * 10);

			/* Multi-line text clamp on description */
			& h4 {
				display: -webkit-box;
				-webkit-line-clamp: 3;
				line-clamp: 2;
				-webkit-box-orient: vertical;
				overflow: hidden;
			}
		}
	}
</style>
