<script lang="ts">
    // --- Components ---
	import { Flex } from '@ui';

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        navigationClass = $bindable(`h-20 justify-between items-center self-stretch box-border`)
    }: Props = $props();


    // Setup Navigation's class
    let navigationCls = $state(cn(navigationClass, className));
    $effect(() => {
        navigationCls = cn(navigationClass, className)
    })

</script>

<Flex.Row class={ navigationCls }>
    {@render children?.()}
</Flex.Row>

<!--@component
    Generated by SvelteForge🔥
-->

