<script lang="ts">
	// --- Components ---
	import { Flex } from '@ui';

	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { ItemProps } from '..';

	let {
		children,
		class: className,

		// --- Default Classes
		itemClass = $bindable('w-35 items-center justify-center'),
		iconClass = $bindable(``),

		// --- User Defined Classes
		classIcon = $bindable(``),

		// Extra Props Here:
		onclick = $bindable(undefined),
		href = $bindable(undefined),

		// Snippets Here:
		icon
	}: ItemProps = $props();

	// Setup Item's class
	let itemCls = $state(cn(itemClass, className));
	let iconCls = $state(cn(iconClass, classIcon));

	$effect(() => {
		itemCls = cn(itemClass, className);
		iconCls = cn(iconClass, classIcon);
	});

	// If this item should act as a link, replace the onclick method
	if (href) {
		onclick = () => {
			window.location.href = href;
		};
	}
</script>

<Flex.Col class={itemCls} {onclick}>
	<!-- Icon Renderer -->
	<Flex.Col class={iconCls}>
		{@render icon?.()}
	</Flex.Col>

	{@render children?.()}
</Flex.Col>

<!--@component
    Generated by SvelteForge🔥
-->
